### ISSUE TITLE
Path to customizer-polylang.js is wrong

### ISSUE THREAD

**Issue by Paike** [soderlind/customizer-polylang#10]
Filename in the repository is `./js/customizer-polylang.js` , but reference is:

https://github.com/soderlind/customizer-polylang/blob/d85c2c2984dda0babc916c19adfc49ce80cba4ea/customizer-polylang.php#L239

Should be fixed to `$src       = get_stylesheet_directory_uri() . '/js/customizer-polylang.js';`

**Comment by soderlind** [comment]
Thank you, renamed to correct filename
