### ISSUE TITLE
Question about forcing Polylang settings.

### ISSUE THREAD

**Issue by hectorfarahani** [soderlind/customizer-polylang#11]
What is the reason to force Polylang setting to "The language is set from content".
Is changing it or removing the following code causeing any issue?
```
/**
 * Force "The language is set from content" (in Language->Settings->URL modifications)
 */
$options = get_option( 'polylang' );
if ( isset( $options['force_lang'] ) && 0 !== $options['force_lang'] ) {
	$options['force_lang'] = 0;
	update_option( 'polylang', $options );
}
```
Thank you.

**Comment by soderlind** [comment]
I copied the code from an in-house project where we prefer "The language is set from content". 

No, I don't believe it will cause an issue removing this code.
