### ISSUE TITLE
Unwanted data in theme mods

### ISSUE THREAD

**Issue by hectorfarahani** [soderlind/customizer-polylang#12]
Issue:
After saving customizer, some unwanted data is adding to the theme mods and it slows down the site.

In order to replicate it please follow these steps:
1. In a clean installation, activate a theme that uses this class.
2. Activate poly lang.
3. Add 2 languages.
4. Save customizer by changing some options multiple times.
5. Check theme_mods in the database and you will see there are too many unwanted data.

The reason:
The initial value of theme mods includes a `false` value. `(`\wp-includes\theme.php`):768`
In multilingual class, `wp_parse_args` is used to avoid missing default values. And it keeps that false value in the array every time and duplicates it.

Possible solution: 
Simply filtering theme mods to remove members with an integer key.
If you confirm this issue, we will be happy to apply the fix and send a pull request.

**Comment by soderlind** [comment]
Good catch, please send a pull request
