### ISSUE TITLE
No media

### ISSUE THREAD

**Issue by nunodonato** [soderlind/customizer-polylang#14]
Trying to change a header image in my 2nd language, I'm faced with an empty image gallery. Shouldn't it be shared among languages?

**Comment by soderlind** [comment]
This is a Polylang setting. By default, I believe, Polylang  activate languages and translations for media. You can disable it in Language→Settings (/wp-admin/admin.php?page=mlang_settings).

**Comment by nunodonato** [comment]
You are right, sorry about that! and thanks for the great tool :)
