### ISSUE TITLE
Languages not loaded

### ISSUE THREAD

**Issue by peterfication** [soderlind/customizer-polylang#2]
Hey there,

thanks for the collection of this plugin. Unfortunately, I couldn't get it to work properly.

```
// This did not work for me
get_option('_transient_pll_languages_list')
// This also didn't work in the `customizer-polylang.php` but on normal pages it worked
pll_the_languages(array('raw'=>1));
```

That's why I hard coded my languages for now.

Furthermore, the option `page_on_front` does not like to be updated. So I excluded it for now.

Do you have any idea what I might have done wrong?

**Comment by pablo-sg-pacheco** [comment]
I couldn't make it work too :(

**Comment by pablo-sg-pacheco** [comment]
Hi @peterfication,
I just created a new pull request with the fix and I ended up adding Composer too:
https://github.com/soderlind/customizer-polylang/pull/3

My problem was the JS path

**Comment by soderlind** [comment]
#4 is merged, should fix this issue.
