### ISSUE TITLE
Customizer does not change content

### ISSUE THREAD

**Issue by SimonVanacco** [soderlind/customizer-polylang#5]
Hi,
I installed the plugin in hopes that it would solve my customizing-translation-problems, but i can't quite get it to work. 

I followed instructions & installed the files. Now the customizer has the language options at the top, but whatever i choose, it will save changes to an option for all language. 
(For exemple if a choose "English" and then edit a string, if i go back to "French", the string also has been updated)

Have i made a mistake? 
Thanks,
Simon

**Comment by soderlind** [comment]
I'm refactoring, and have found a couple of bugs. Will post an update as soon as I have a fix. I also plan to add support for [add|get]_theme_support().

**Comment by SimonVanacco** [comment]
Thanks for the answer! Will be quite happy to implement as soon as it is fixed!
Have a great day,
Simon

**Comment by soderlind** [comment]
Fixed in latest release
