### ISSUE TITLE
Error: Using require once gives error

### ISSUE THREAD

**Issue by dadodd** [soderlind/customizer-polylang#8]
Hello, thank you for great plugin.

I am not sure is it is https related, but when using

``require_once get_stylesheet_directory_uri() '/customizer-polylang.php';``

I get error :

Warning: require_once(): http:// wrapper is disabled in the server configuration by allow_url_include=0
Fatal error: require_once(): Failed opening required

Also I think correct way for this would be: 

`require_once( get_stylesheet_directory(). '/my_included_file.php' ); `

as per: https://developer.wordpress.org/themes/advanced-topics/child-themes/

But i still couldn't get it to work, so instead I used:

`include  STYLESHEETPATH . '/customizer-polylang.php';
`

**Comment by soderlind** [comment]
Yep, you are correct. You should use `require_once  get_stylesheet_directory(). '/customizer-polylang.php';`

I found a bug at line 239: It should use `get_stylesheet_directory_uri()`
https://github.com/soderlind/customizer-polylang/blob/a12347f84f127efbc95c93c4bdadcc95402d972c/customizer-polylang.php#L239

I'll fix it asap

**Comment by soderlind** [comment]
I've fixed the bug. Thank you for reporting this :)

**Comment by dadodd** [comment]
Thanks for the quick fix.

I have looked your code, you have another bug, at the moment it doesnt work, but when path fixed plugin is working :)

Line 239

`$src       = get_template_directory_uri() . '/inc/customizer/assets/js/polylang-customizer.js'; 0
`
to
`$src       = get_template_directory_uri() . '/js/customizer-polylang.js'; 
`

**Comment by soderlind** [comment]
@dadodd Again, thank you. I was a bit quick when I moved the code from an internal project.
