### ISSUE TITLE
Missing Customizer Language Switcher in new version.

### ISSUE THREAD

**Issue by ryanlabelle** [soderlind/customizer-polylang#9]
In the new version of the customizer-polylang script, the switcher is missing.

https://cl.ly/6220c48b48ea

Perhaps I'm missing a step. 

- [x] Polylang must be installed and activated.
- [x] Add languages in Admin->Languages.
- [ ] If you have a static front page: Create a front page per language. In Admin->Settings-Reading, per language, select the front page.
I don't see the 'Per Language' option under my settings. https://cl.ly/9ddcdf4d623d  ...but I do have a home page that is translated into both of my setup languages.
- [ ] Expect customizer to use setting type = theme_mod (the customizer default) as in:
```
$wp_customize->add_setting( 'setting_id', [
	'type' => 'theme_mod', // the default, you don't have to set this
 ] );
```
This is where I'm getting a little lost as I am using a default install of the Twenty-Nineteen theme, so I have nothing custom set for this. Do I need to?

Thank you so much for your help.

**Comment by Paike** [comment]
I just realized, my issue #10 is related to this:

Filename in the repository is `./js/customizer-polylang.js` , but reference is:

https://github.com/soderlind/customizer-polylang/blob/d85c2c2984dda0babc916c19adfc49ce80cba4ea/customizer-polylang.php#L239

Should be fixed to `$src       = get_stylesheet_directory_uri() . '/js/customizer-polylang.js';`

I did not know, that there should be a language switcher, but after the fix it shows.

**Comment by soderlind** [comment]
Thank you, fixed
